### ISSUE TITLE
Add a feature flag for dynamic vs static linking the vendor driver.

### ISSUE THREAD

**Issue by newAM** [newAM/libftd2xx-ffi-rs#10]
As titled.

Windows will likely have to occur separately as there are challenges see [here](https://github.com/newAM/libftd2xx-ffi-rs/pull/9#pullrequestreview-559709230) and [here](https://github.com/newAM/libftd2xx-ffi-rs/pull/9#issuecomment-752261656).

**Comment by newAM** [comment]
It's fine by me to make a breaking change to align platforms to static linking by default, this is still pre-1.0 to account for these TODO's. 😀

**Comment by Grinkers** [comment]
Bleh, I thought I had a decent way to find the path such as:
"C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\lib\\x64"

The only thing I can really think of right now is pull in this exe as a dependency to find the install path and then recursively look for the correct .lib files. https://github.com/microsoft/vswhere

On Windows, test is blowing up with `__NULL_IMPORT_DESCRIPTOR already defined in ftd2xx.lib(ODBC32.dll)` even though the compiled library works (both when linked into a binary or dll) without further dependencies. I think I came full circle and ended up where your static branch ended up. 

https://github.com/newAM/libftd2xx-ffi-rs/compare/main...Grinkers:static_dynamic I will battle test it a bit, then look into fixing the lib path and linking itself (tests).

**Comment by newAM** [comment]
I had an idea a while ago that I never explored.  Can we replace the symbols needed?

## `legacy_stdio_definitions`

> unresolved external symbol __imp_printf referenced in function "int __cdecl DumpDeviceWithInfo(void *,struct _SP_DEVINFO_DATA *,char const *)"

## `user32`

> unresolved external symbol __imp_CharNextA referenced in function "int __cdecl EnumerateDevices(char const *,char const *,unsigned long,int,wchar_t * *,int (__cdecl*)(void *,struct _SP_DEVINFO_DATA *,unsign
ed long,void *),void *)"

> unresolved external symbol __imp_CharPrevA referenced in function "void __cdecl FormatToStream(struct _iobuf *,unsigned long,...)"

---

`user32` does not seem to be a problem, it is included in `System32`, no visual studio path needed.

`legacy_stdio_definitions` only needs one symbol, `__imp_printf`.
Now making a bold assumption that the signature is `int printf(const char *format, ...)` we _could_ just implement this ourselves.

I updated [`static_link_msvc`](https://github.com/newAM/libftd2xx-ffi-rs/tree/static_link_msvc) with a rough idea, it builds & links of my machine without the `legacy_stdio_definitions` thing.
Unfortunately [c_variadic](https://doc.rust-lang.org/beta/unstable-book/language-features/c-variadic.html) is an unstable rust feature right now, so we cannot replace the function in pure rust.

That leads to using the CC crate and providing a C function for `__imp_printf` compiled in the `build.rs`.

Not sure if that leads to a cleaner solution... What do you think?

**Comment by Grinkers** [comment]
I believe the issue is because ftd2xx was compiled with such an old version of VS that some of the defines are different. When I saw that, I was thinking imp_printf would be one of the many functions that got redefined (guess what the solution for that is... dynamic link). However, it seems like it may be possible to just stub out the print. I'm not aware of it actually ever printing, but maybe I just don't use that functionality. I don't think we want to even try reimplementing this, because it probably relies on undocumented internal structures of MS' library. It'll be very important to get both the 32 and 64 bit versions correct without blowing up the stack. Thankfully rust seems to support both cdecl and stdcall without any issue.

I will poke at it this week. I will try both stubbing out imp_printf and hard coding legacy_stdio_defenitions. The library I maintain is dynamically called from programs dating all the way back to vs2005 though 2019. However I suspect a printf stub will break c statically linked programs that use this as a dependency, but in theory we can just feature gate the legacy_stdio_definitions. People on old VS can opt-out of the stub.

Just last night I actually started looking at helping stabilize c_variadic. It's the last thing holding me back from "using rust with c libraries" vs "using c with rust libraries". However in this case, I don't think we'll need it either way, because we probably don't want a real implementation.

**Comment by newAM** [comment]
> I'm not aware of it actually ever printing, but maybe I just don't use that functionality.

I wonder if `DumpDeviceWithInfo` is just a debug symbol that is never actually called, it seems like this is part of some sample code FTDI copy and pasted from Microsoft.

https://github.com/microsoft/Windows-driver-samples/blob/c3b354b79a46a20e7a8063bb69e24d3f7883ce67/setup/devcon/dump.cpp#L18

> I don't think we want to even try reimplementing this, because it probably relies on undocumented internal structures of MS' library. It'll be very important to get both the 32 and 64 bit versions correct without blowing up the stack.

That is true, this is rust were there are higher developer expectations for safety and soundness... Probably not a good idea to have a glaring exception to that rule.

**Comment by Grinkers** [comment]
Trying to stub out print quickly leads to 

```
liblibftd2xx_ffi-244e410205eca39c.rlib(devcon.obj) : error LNK2019: unresolved external symbol __imp_CharNextA referenced in function "int __cdecl EnumerateDevices(char const *,char const *,unsigned long,int,wchar_t * *,int (__cdecl*)(void *,struct _SP_DEVINFO_DATA *,unsigned long,void *),void *)" (?EnumerateDevices@@YAHPEBD0KHPEAPEA_WP6AHPEAXPEAU_SP_DEVINFO_DATA@@K2@Z2@Z)

liblibftd2xx_ffi-244e410205eca39c.rlib(devcon.obj) : error LNK2019: unresolved external symbol __imp_CharPrevA referenced in function "void __cdecl FormatToStream(struct _iobuf *,unsigned long,...)" (?FormatToStream@@YAXPEAU_iobuf@@KZZ)

``` 
when trying to link against this library. Things seem to work fine passing in the legacy_stdio_definitions and user32 libs.

 
I'm convincing myself we should default with dynamic linking. On Windows, it's the 'correct' thing to do. There's certainly precedence on Linux to install the .so system-wide so all programs can use it. It has a nice benefit of just a dll/so swap if FTDI has bug fixes too.

**Comment by Grinkers** [comment]
https://github.com/newAM/libftd2xx-ffi-rs/compare/main...Grinkers:static_dynamic

This is what I've come up with so far. I'm using an os variable "LIBMSVC_PATH", not unlike bindgen
does with "LIBMSVC_PATH", like
https://github.com/rust-lang/rust-bindgen/blob/8ac787a9b4fab937533b964a3ee8d0bff840bf08/book/src/requirements.md#installing-clang-39

In this iteration of the dynamic/static WIP, I've made dynamic linking the default. I think this is
best because it's just the 'better' (certainly easier) thing to do on Windows. Additionally, on GNU systems, the static
linking between anything GPL and the FTDI library could cause some licensing problems. Of course the
user would be required to manage installing the .so, just like on Windows with the dll.

![dyn_static_on_ms](https://user-images.githubusercontent.com/10585431/107161692-c050a200-69e1-11eb-8ab9-5f3dd15d122b.png)
Just for reference, this is what it looks like on Windows compiling an exe with default (dynamic) and features=static.

**Comment by newAM** [comment]
> If you have any ideas/recommendations, I'd like to hear it. If not, I can update the readme and then squash/PR.

That's a real clean implementation, looks good to me!
