### ISSUE TITLE
Licensing (Attribution)

### ISSUE THREAD

**Issue by Grinkers** [newAM/libftd2xx-ffi-rs#30]
I'd like to bring up the topic of the license. I'm not a license expert and don't want to start any trouble. Feel free to immediately close or delete this "Issue" without any acknowledgment.

The only 'issue' is the MIT license requires license/copyright notices and attribution, which is an additional requirement not part of the FTDI D2XX license.

However, because this is a bindings only project (unlike https://github.com/newAM/libftd2xx-rs), I'm not entirely sure where this falls. In theory, no code from this repo will actually end up in a compiled binary with this repo as a depnedency. For example, using the bindgen feature will execute code from this repository, but none of it will end up in any compiled binary using this repo as a dependency. In this example, I think it's more of a build tool than a library? Without the bindgen feature, I'm not sure where things fit.

I'm thinking perhaps a dual license MIT and a public domain license or zero-clause BSD may make this a complete non-issue?

Thanks for reading. Special thanks for any clarification on how a bindings crate gets classified.

**Comment by newAM** [comment]
That is a good point.

Technically this crate also distributes the FTD2xx binary (with permission from FTDI), I should probably use the license file field instead of blindly licensing this as "MIT" as well.  This will kill some automated licensing trawlers, but this is the kind of crate people probably want to be aware of.

I updated the license to dual MIT/0BSD (for the bindings) in this PR: https://github.com/newAM/libftd2xx-ffi-rs/pull/31
Let me know if that works for you.

**Comment by Grinkers** [comment]
Looks good to me. I think this completely solves the issue. 

I agree this is the kind of crate that should make people aware of the the FTDI licensing.

**Comment by newAM** [comment]
Excellent, merged.

There should be a release this weekend after I finish #29
